### Simple Query
GRAPHQL http://{{host}}/graphql
Content-Type: application/graphql

query GetUser {
  user(id: 3) {
    id
    email
  }
}

### Simple Query
GRAPHQL http://{{host}}/graphql
Content-Type: application/graphql

query GetUsers {
  users {
    id
    email
  }
}

### Simple Mutation
GRAPHQL http://{{host}}/graphql
Content-Type: application/graphql

mutation CreateUser($newUser: NewUser!) {
  createUser(newUser: $newUser){
    id
    email
  }
}

{
  "newUser": {
    "email": "test8@example.com",
    "password": "123456",
    "firstName": "John",
    "lastName": "Doe"
  }
}

### Subscriptions over WebSockets
// WebSockets are handy for GraphQL subscriptions
GRAPHQL http://{{host}}/graphql

subscription Subscription {
  randomHuman {
    id
    email
  }
}
