create domain email as varchar(256)
    check (value ~
           '^[a-zA-Z0-9.!#$%&''*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$');

create table if not exists users
(
    id         bigint primary key generated by default as identity,
    email      email unique not null,
    password   bytea not null,
    first_name text,
    last_name  text,
    created_at timestamptz not null default now(),
    deleted_at timestamptz
);
